# Generated by Django 3.2.13 on 2022-06-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='グループ名')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='名前')),
                ('auth', models.BooleanField(default=False, verbose_name='権限A')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mst.group')),
            ],
        ),
    ]
