# Generated by Django 3.2.13 on 2022-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
