# Generated by Django 3.2.13 on 2022-06-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mst', '0002_auto_20220602_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
